---
- name: Validate AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN vars
  command: aws sts get-caller-identity
  args:
    warn: no
  register: result

- name: Display result of AWS vars validation
  debug:
    var: result.stdout_lines

